<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Atlas" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/faults"
    nsPrefix="flt">
  <eClassifiers xsi:type="ecore:EClass" name="TimeProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="faultRepeatCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fault">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedRegion" lowerBound="1"
        eType="ecore:EClass region.ecore#//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedTime" lowerBound="1"
        eType="#//TimeProperties" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impact" lowerBound="1"
        eType="#//FaultImpact" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FaultImpact" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MessageImpact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedMessage" upperBound="-1"
        eType="ecore:EClass message.ecore#//Message" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelayMessage" eSuperTypes="#//MessageImpact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="delayLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteMessage" eSuperTypes="#//MessageImpact"/>
  <eClassifiers xsi:type="ecore:EClass" name="MutateMessage" eSuperTypes="#//MessageImpact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedField" upperBound="-1"
        eType="ecore:EClass message.ecore#//MessageField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="newValue" lowerBound="1"
        eType="#//MessageChange" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageChange" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntMessageChange" eSuperTypes="#//MessageChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incrementValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringMessageChange" eSuperTypes="#//MessageChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatMessageChange" eSuperTypes="#//MessageChange">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absoluteValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incrementValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentImpact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affectedComponent" lowerBound="1"
        eType="ecore:EClass components.ecore#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisabledComponent" eSuperTypes="#//ComponentImpact"/>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyLoss" eSuperTypes="#//ComponentImpact">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedEnergyLoss" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="powerDraw" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
