<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FuzzingExpt" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/fuzzingexpt"
    nsPrefix="fuzzingexpt">
  <eClassifiers xsi:type="ecore:EClass" name="ParticipantChoice" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecificParticipantChoice" eSuperTypes="#//ParticipantChoice">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//NamedComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllParticipantChoice" eSuperTypes="#//ParticipantChoice"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimingSpec" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingSelection" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participantChoice" lowerBound="1"
        eType="#//ParticipantChoice" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opParams" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping#//OperationParameterSet"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timspec" lowerBound="1"
        eType="#//TimingSpec" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentFuzzingSelection" eSuperTypes="#//FuzzingSelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentChoice" lowerBound="1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping#//FuzzingComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableFuzzingSelection" eSuperTypes="#//FuzzingSelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varChoice" lowerBound="1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping#//VariableSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFuzzingSelection" eSuperTypes="#//FuzzingSelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msgChoice" lowerBound="1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping#//FuzzingMessage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messageField" lowerBound="1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping#//VariableSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingExperiment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sels" upperBound="-1" eType="#//FuzzingSelection"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
