<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Fuzzing" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/fuzzing"
    nsPrefix="fuzzing">
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingEntitySelection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingOperation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableFuzzing" eSuperTypes="#//FuzzingEntitySelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="varToFuzz" eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping#//VariableSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentFuzzing" eSuperTypes="#//FuzzingEntitySelection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFuzzing" eSuperTypes="#//FuzzingEntitySelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg" eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/message#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeDoubleChange" eSuperTypes="#//FuzzingOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxChange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstantDoubleChange" eSuperTypes="#//FuzzingOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingInfoRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ftype" upperBound="-1"
        eType="#//FuzzingEntitySelection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//FuzzingOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relevantVehicles" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//Robot"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="records" upperBound="-1"
        eType="#//FuzzingInfoRecord" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
