<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Atlas" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/mission"
    nsPrefix="atlas">
  <eClassifiers xsi:type="ecore:EClass" name="GoalResultField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntResultField" eSuperTypes="#//GoalResultField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringResultField" eSuperTypes="#//GoalResultField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatResultField" eSuperTypes="#//GoalResultField">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RobotResultField" eSuperTypes="#//GoalResultField"/>
  <eClassifiers xsi:type="ecore:EClass" name="PointResultField" eSuperTypes="#//GoalResultField"/>
  <eClassifiers xsi:type="ecore:EClass" name="GoalResult">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//GoalResultField" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalAction" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Visit" eSuperTypes="#//GoalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Patrol" eSuperTypes="#//GoalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Cover" eSuperTypes="#//GoalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Avoid" eSuperTypes="#//GoalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="StayInRegion" eSuperTypes="#//GoalAction"/>
  <eClassifiers xsi:type="ecore:EClass" name="AvoidOthers" eSuperTypes="#//GoalAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clearance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscoverObjects" eSuperTypes="#//GoalAction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/region#//EnvironmentalObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="robotsNeededPerObject"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorCover" eSuperTypes="#//Cover">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="density" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="samplesPerUnit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensortype" eType="ecore:EEnum http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//SensorType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collective" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalParticipants" abstract="true"/>
  <eClassifiers xsi:type="ecore:EEnum" name="logicOps">
    <eLiterals name="ADD" value="1"/>
    <eLiterals name="SUBTRACT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeParticipants" eSuperTypes="#//GoalParticipants">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentGoal" eType="#//Goal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticRobots" eType="#//StaticParticipants"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="setOperation" eType="#//logicOps"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="participantLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StaticParticipants" eSuperTypes="#//GoalParticipants">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//Robot"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalTemporalConstraints">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Goal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="earliestStartTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latestFinishTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GoalRegion" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="StaticGoalRegion" eSuperTypes="#//GoalRegion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="staticRegion" eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/region#//Rectangle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicGoalRegion" eSuperTypes="#//GoalRegion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relativeToGoal" lowerBound="1"
        eType="#//Goal"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeToGoalField" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeRange" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requirements" eType="#//GoalTemporalConstraints"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participants" eType="#//GoalParticipants"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" eType="#//GoalAction"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="region" eType="#//GoalRegion"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="robots" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//Robot"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="computers" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//Computer"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="regions" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/region#//Region"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/region#//EnvironmentalObject"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="obstacles" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/region#//EnvironmentalObstacle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="messages" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/message#//Message"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faults" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/faults#//Fault"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
