<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Atlas" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/region"
    nsPrefix="atlas">
  <eClassifiers xsi:type="ecore:EClass" name="Region" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="corner1" lowerBound="1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="corner2" lowerBound="1"
        eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Circle" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="centre" lowerBound="1"
        eType="#//Point" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="radius" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" lowerBound="2"
        upperBound="-1" eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Polygon" eSuperTypes="#//Region">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" lowerBound="3"
        upperBound="-1" eType="#//Point" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalObject" eSuperTypes="#//Point">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isHazard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalObstacle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="poly" eType="#//Polygon"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
