<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Simmapping" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/simmapping"
    nsPrefix="simmapping">
  <eClassifiers xsi:type="ecore:EClass" name="Simulator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseDirectory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableDirection">
    <eLiterals name="INBOUND" value="1"/>
    <eLiterals name="OUTBOUND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableNature">
    <eLiterals name="BINARY" value="1"/>
    <eLiterals name="CONFIG" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableSpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sim" lowerBound="1" eType="#//Simulator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dir" eType="#//VariableDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//VariableNature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopologySpecification">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sim" lowerBound="1" eType="#//Simulator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg" lowerBound="1" eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/message#//Message"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specs" upperBound="-1"
        eType="#//VariableSpecification" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableMappings">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vars" upperBound="-1" eType="#//VariableSpecification"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
