<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Fuzzing" nsURI="http://www.github.com/jrharbin-york/atlas-middleware/dsl/fuzzing"
    nsPrefix="fuzzing">
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingEntitySelection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingOperationParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="param" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="className" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opParams" eType="#//FuzzingOperationParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableFuzzing" eSuperTypes="#//FuzzingEntitySelection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varNameToFuzz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentFuzzing" eSuperTypes="#//FuzzingEntitySelection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="component" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MessageFuzzing" eSuperTypes="#//FuzzingEntitySelection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="msg" eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/message#//Message"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimingSpec" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntireTime" eSuperTypes="#//TimingSpec"/>
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTime" eSuperTypes="#//TimingSpec">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubSpecSelection" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericSubSpecSelection" eSuperTypes="#//SubSpecSelection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingInfoRecord">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ftype" upperBound="-1"
        eType="#//FuzzingEntitySelection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//FuzzingOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relevantVehicles" upperBound="-1"
        eType="ecore:EClass http://www.github.com/jrharbin-york/atlas-middleware/dsl/components#//Robot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TimingSpec" eType="#//TimingSpec"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subspec" eType="#//SubSpecSelection"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzingSpec">
    <eStructuralFeatures xsi:type="ecore:EReference" name="records" upperBound="-1"
        eType="#//FuzzingInfoRecord" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
