gilda-narrow,frank-narrow,ella-wide
gilda-narrow,frank-narrow,henry-wide,ella-narrow
frank-narrow,henry-wide,ella-narrow
gilda-narrow,frank-wide,ella-wide
gilda-narrow,frank-wide,henry-wide,ella-narrow
gilda-narrow,frank-wide,henry-narrow,ella-wide
gilda-narrow,frank-narrow,henry-narrow,ella-wide
gilda-narrow,frank-wide,henry-narrow,ella-narrow
gilda-narrow,frank-wide,henry-wide,ella-wide
gilda-narrow,frank-narrow,henry-wide,ella-wide
gilda-narrow,henry-narrow,ella-wide
gilda-narrow,frank-narrow,henry-narrow,ella-narrow
gilda-narrow,frank-narrow,henry-wide
gilda-narrow,henry-wide,ella-wide
