gilda-wide,frank-narrow,henry-narrow,ella-narrow
gilda-wide,frank-wide,henry-narrow,ella-narrow
gilda-wide,frank-wide,henry-wide,ella-wide
gilda-wide,frank-wide,ella-wide
frank-wide,henry-wide,ella-wide
gilda-wide,frank-wide,henry-narrow,ella-wide
gilda-wide,frank-narrow,ella-wide
gilda-wide,frank-narrow,henry-wide,ella-narrow
gilda-wide,frank-narrow,henry-narrow,ella-wide
gilda-wide,frank-wide,henry-wide
gilda-wide,frank-narrow,henry-wide
gilda-wide,frank-wide,henry-wide,ella-narrow
frank-narrow,henry-wide,ella-wide
gilda-wide,frank-narrow,henry-wide,ella-wide
