<cond> ::= <var> <bincomp> <expr>
<var> ::= .testvar1 | .testvar2 | .testvar3
<bincomp> ::= .LESS_THAN | .GREATER_THAN | .EQUALS | .NOT_EQUALS
<expr> ::= <var> | <int>
<int> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
