package exptrunner.metrics;

public enum Metrics {
	PURE_MISSED_DETECTIONS,
	COMBINED_MISSED_DETECTION_DIST_METRIC,
	AVOIDANCE_METRIC,
	TIME_PROP,
	TIME_TOTAL_ABSOLUTE,
	NUM_FAULTS,
	FIRST_FAULT_TIME,
	DETECTION_COMPLETION_TIME,
	OBSTACLE_AVOIDANCE_METRIC,
	OUTSIDE_REGION_COUNT,
	TOTAL_ENERGY_AT_END,
	MEAN_ENERGY_AT_END,
	TOTAL_FINAL_DISTANCE_AT_END,
	MEAN_FINAL_DISTANCE_AT_END,
	TOTAL_WAYPOINT_SWITCH_COUNT,
	WORST_CASE_WAYPOINT_COMPLETION_FROM_CI
};
